const actionTypes = {
  SAVE_RESULT: "SAVED_RESULT",
  SET_THRESHOLD: "SET_THRESHOLD",
  SET_KCOUNT: "SET_KCOUNT",
  RESTORE_ORIGINAL: "RESTORE_ORIGINAL",
  IMAGE_CLUSTERIZE: "IMAGE_CLUSTERIZE",
  IMAGE_THRESHOLD: "IMAGE_THRESHOLD",
  IMAGE_GRAYSCALE: "IMAGE_GRAYSCALE",
  IMAGE_CUMULATIVE: "IMAGE_CUMULATIVE",
  IMAGE_HISTOGRAM: "IMAGE_HISTOGRAM",
  IMAGE_CUMULATIVE_CLUSTERIZED: "IMAGE_CUMULATIVE_CLUSTERIZED",
  IMAGE_HISTOGRAM_CLUSTERIZED: "IMAGE_HISTOGRAM_CLUSTERIZED",
  PROCEED_IMAGE: "PROCEED_IMAGE",
  LOAD_PATTERN: "LOAD_PATTERN",
  LOAD_ETALON: "LOAD_ETALON",
  DETECT_DEFECTS: "DETECT_DEFECTS",
};
export default actionTypes;
