const actionTypes = {
  LOAD_IMAGE: "LOAD_IMAGE",
  SAVE_RESULT: "SAVED_RESULT",
  INIT_CANVAS: "INIT_CANVAS",
  CLEAR_CANVAS: "CLEAR_CANVAS",
  SET_THRESHOLD: "SET_THRESHOLD",
  SET_KCOUNT: "SET_KCOUNT",
  RESTORE_ORIGINAL: "RESTORE_ORIGINAL",
  IMAGE_CLUSTERIZE: "IMAGE_CLUSTERIZE",
  IMAGE_THRESHOLD: "IMAGE_THRESHOLD",
  IMAGE_GRAYSCALE: "IMAGE_GRAYSCALE",
  IMAGE_CUMULATIVE: "IMAGE_CUMULATIVE",
  IMAGE_CUMULATIVE_CLUSTERIZED: "IMAGE_CUMULATIVE_CLUSTERIZED",
  PROCEED_IMAGE: "PROCEED_IMAGE",
  LOAD_PATTERN: "LOAD_PATTERN",
  LOAD_ETALON: "LOAD_ETALON",
};
export default actionTypes;
